//! Authoring SDK for `hm` plugins.
//!
//! Plugins build to `cdylib` (native shared libraries). The host
//! loads each plugin via `stabby`'s ABI-stable trait objects: the
//! plugin implements [`ffi::RawPlugin`] (generated by the
//! [`hm_plugin!`] macro), while the host provides
//! [`ffi::RawHostApi`] wrapped in a [`PluginContext`].
//!
//! User-facing capability traits ([`StepExecutor`], [`LifecycleHook`],
//! [`SubcommandPlugin`], [`OutputFormatter`]) are async and receive a
//! `&PluginContext` so they can call host functions ergonomically.
//!
//! ```ignore
//! use hm_plugin_sdk::*;
//!
//! #[derive(Default)]
//! struct MyExec;
//! impl StepExecutor for MyExec {
//!     fn run<'a>(&'a self, ctx: &'a PluginContext<'a>, input: ExecutorInput)
//!         -> impl Future<Output = Result<StepResult, PluginError>> + Send + 'a
//!     {
//!         async move {
//!             ctx.log(Level::Info, &format!("running {}", input.step.key));
//!             Ok(StepResult { exit_code: 0, committed_snapshot: None, artifacts: vec![] })
//!         }
//!     }
//! }
//! ```

// stabby's generated vtable code uses unsafe FFI trampolines, so this
// crate cannot use `#![forbid(unsafe_code)]`.
//
// schemars 0.8 pulls older indexmap and wit-bindgen via its transitive tree
// (inherited through hm-plugin-protocol). Keep the same crate-level allows as
// the protocol crate so noisy cargo-group lints don't drown out real issues.
#![allow(clippy::multiple_crate_versions, clippy::cargo_common_metadata)]

pub mod context;
pub mod executor;
pub mod ffi;
pub mod hook;
pub mod output;
pub mod subcommand;

#[doc(hidden)]
pub mod macros;

pub use context::PluginContext;
pub use executor::StepExecutor;
pub use hm_plugin_protocol::*;
pub use hook::LifecycleHook;
pub use macros::hm_plugin;
pub use output::OutputFormatter;
pub use subcommand::SubcommandPlugin;
