[package]
name = "hm-fixture-bad-api-version"
version = "0.0.0"
publish = false
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
hm-plugin-sdk      = { workspace = true }
hm-plugin-protocol = { workspace = true }
stabby             = { workspace = true }
borsh              = { workspace = true }
serde              = { workspace = true }
semver             = { workspace = true }

[lints]
workspace = true
