[package]
name = "hm-plugin-sdk"
version = "0.0.0-dev"
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Authoring SDK for hm plugins. Defines hm-specific traits and macros."

[lib]
crate-type = ["rlib"]

[dependencies]
hm-plugin-protocol = { workspace = true }
hm-plugin-macros   = { workspace = true }
stabby             = { workspace = true }
borsh              = { workspace = true }
serde              = { workspace = true }
serde_json         = { workspace = true }
clap               = { version = "4", features = ["string"] }

[dev-dependencies]
clap   = { version = "4", features = ["derive"] }
semver = { workspace = true }

[lints]
workspace = true
